### PR TITLE
Update to add `--ignore-rekor` to the CLI example

### PR DESCRIPTION
**Pull request by seanconroy2021**
Found that we haven't update the user guide CLI example to include `--ignore-rekor` 
Ref: n/a

### CODE REVIEW

**Comment by zregvart** [comment]
Folk might be using Rekor, e.g. the public instance, so not sure...

**Comment by lcarva** [comment]
I think we need `--ignore-rekor` here because of the example image above. Maybe we need to add blurb after shell script that says something like: "The image used in this example was signed and attested without using Rekor. This is why the `--ignore-rekor` flag is needed"

**Comment by simonbaird** [comment]
I like Luiz' suggestion. Otherwise lgtm.

**Comment by seanconroy2021** [comment]
I added a note under the shell

**Review by zregvart — APPROVED** [review]

**Pull request merged**
